# Cloud Build configuration for LicitaReview Analyzer Service (RAG-enabled)
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/analyzer-rag:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/analyzer-rag:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/analyzer-rag:v2.0.0'
      - '.'
    dir: 'services/analyzer'

  # Push tagged image with build ID
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/analyzer-rag:$BUILD_ID'

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/analyzer-rag:latest'

  # Push version tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/analyzer-rag:v2.0.0'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'analyzer-rag'
      - '--image=gcr.io/$PROJECT_ID/analyzer-rag:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--concurrency=80'
      - '--max-instances=20'
      - '--min-instances=1'
      - '--timeout=300'
      - '--set-env-vars=^@^GCP_PROJECT_ID=${PROJECT_ID}@GCP_LOCATION=us-central1@GCS_RAG_BUCKET=${PROJECT_ID}-rag-corpus@RAG_CHUNK_SIZE=512@RAG_CHUNK_OVERLAP=100@RAG_EMBEDDING_MODEL=text-embedding-004@RAG_DEFAULT_MODEL=gemini-2.0-flash-001@RAG_DEFAULT_TEMPERATURE=0.3@RAG_DEFAULT_TOP_K=10@REDIS_ENABLED=true@CACHE_TTL_SECONDS=3600@PYTHONPATH=/app/src'
      - '--service-account=analyzer-rag@${PROJECT_ID}.iam.gserviceaccount.com'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/analyzer-rag:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/analyzer-rag:latest'
  - 'gcr.io/$PROJECT_ID/analyzer-rag:v2.0.0'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build (20 minutes)
timeout: '1200s'
